version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_nodejs
  publisher:
    build:
      context: ./
      target: dev 
    volumes:
      - .:/src
    depends_on:
      - "rabbitmq"
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node new_task.js'
    environment:
      NODE_ENV: development
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      EXIT_TIME: 500000
    networks:
      - rabbitmq_nodejs
  consumer:
    build:
      context: ./
      target: dev
    ports:
        - 4001:4000  
    volumes:
      - .:/src
    depends_on:
      - "publisher"
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node worker.js'
    environment:
      NODE_ENV: development
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbitmq_nodejs
networks:
  rabbitmq_nodejs:
    driver: bridge